title: "蜉蝣人生"
email:
description: "人生大部分时间都是在寻找，寻找喜欢做的事情，寻找需要做的事情"
baseurl: ""
url: "https://belber.github.io"
author: belber

# 文章链接格式
permalink: /diary/:year/:month/:day/:title/

# 构建设置
markdown: kramdown
future: true
timezone: Asia/Shanghai
theme: null       # 不使用主题，完全自定义布局

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - vendor
