backend:
  name: github
  repo: belber/belber.github.io
  branch: main
  auth_type: pkce

publish_mode: editorial_workflow
media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "文章"
    label_singular: "文章"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss Z" }
      - { label: "正文", name: "body", widget: "markdown" }

  - name: "pages"
    label: "页面"
    files:
      - name: "about"
        label: "关于页面"
        file: "about.md"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - { label: "正文", name: "body", widget: "markdown" }
